#' List MAF split output files
#'
#' Given the original MAF filename and output directory,
#' this returns a sorted list of split MAF files generated by `split_maf()`.
#'
#' @param file_in Original input MAF file.
#' @param dir_out Directory containing the split files.
#'
#' @return A character vector of full paths to the split files, sorted by suffix.
#' @export
list_split_maf_files <- function(file_in, dir_out) {
  base_name <- basename(file_in)
  pattern <- paste0("^", base_name, "\\.\\d+$")
  split_files <- list.files(dir_out, pattern = pattern, full.names = TRUE)
  return(sort(split_files))
}
